
add_subdirectory("prototypes")

add_files("leaf-framework"
	"database.hpp"
	"local_string.hpp"
	"localization.cpp"
	"localization.hpp"
	"mod_enabled.cpp"
	"mod_enabled.hpp"
	"mod_info.cpp"
	"mod_info.hpp"
	"mod_loader.cpp"
	"mod_loader.hpp"
	"prototype.hpp"
	"prototype_inspection.hpp"
	"prototype_inspector_script.cpp"
	"prototype_inspector_script.hpp"
	"registry.hpp"
	"settings.hpp"
	"virtual_filesystem.cpp"
	"virtual_filesystem.hpp"
)
